# Spring properties
spring:
  application:
     name: customer-web  # Service registers under this name

info:
  app:
    name: customer-web
    description: Customer Web
    version: 1.0.0

# HTTP Server
server:
  contextPath: /customer-web
  port: 4444   # HTTP (Tomcat) port

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
      statusPageUrlPath: /customer-web/info
      healthCheckUrlPath: /customer-web/health

